fix: pin cmdliner to 1.x.x (#101)
Cmdliner 2.0.0 has changed some interfaces such that `semgrep` no longer
compiles against it:

```
$ opam exec -- make core
...
File "OSS/libs/commons/Cmdliner_.ml", line 135, characters 2-19:
135 |   (parser, printer)
        ^^^^^^^^^^^^^^^^^
Error: This expression has type 'a * 'b
       but an expression was expected of type int Arg.conv
File "OSS/libs/ocaml-tree-sitter-core/src/run/lib/Main.ml", line 119, characters 4-13:
119 |     Term.info
          ^^^^^^^^^
Error: Unbound value Term.inf
```

As a result, semgrep's homebrew version bump has been failing.
This patch simply constrains this dependency to major verson 1.

Tested locally against a fresh opam switch and can confirm that `make
core` now succeeds.