fix(windows): produce valid c_library_flags.sexp on Windows
Followup to https://github.com/semgrep/ocaml-tree-sitter-core/pull/95

The c_library_flags.sexp file needs to hold an s-expression, but on
windows it was being left as an empty file. As a result, builds from
parsers generated with the template would fail in windows with errors
like:

```
File "_build/default/OSS/languages/lisp/tree-sitter/semgrep-clojure/lib/c_library_flags.sexp", line 1, characters 0-0:
Error: no s-expression found in input
```

The fix is just to ensure we output an empty s-expression into the c_library_flags.sexp
on windows.